INSERT INTO category(id, name) VALUES
(1, 'KUCNIA WŁOSKA'),
(2, 'KUCHNIA FRANCUSKA'),
(3, 'KUCHNIA POLSKA');


INSERT INTO recipe(id, name, ingredients, description, category_id, jpg)
VALUES
(1, 'RISOTTO ALLA MILANESE', 'szynka parmeńska – 3 plastry, szalotka – 1 szt., czosnek – 1 ząbek, bulion warzywny – 1 l, świeży rozmaryn – 1 gałązka, olej z pestek winogron – 2 łyżki, ryż arborio – 200 g, szafran – 1 szczypta, białe wytrawne wino – 150 ml, masło – 100 g, parmezan – 50 g, skórka starta z ½ cytryny', 'Klasyka włoskiej kuchni prosto z Mediolanu, wzbogacona o kilka dodatków, wg przepisu Karola Okrasy! Przygotuj wykwintne risotto z szafranem na wyjątkową okazję!', 1, '/jpg/RISOTTO_ALLA_MILANESE.jpg'),
(2, 'MAKARON Z KURCZAKIEM I PESTO Z RUKOLI', 'liście rukoli – 3 szklanki, oliwa – 4 łyżki, orzechy włoskie – 2 łyżki, ser feta – 150 g, sok z limonki – 2 łyżki, syrop z agawy – 1 łyżka', 'Szybki, prosty i pyszny makaron z zielonym pesto, warzywami i kurczakiem będzie świetną opcją, gdy zechcesz podać na obiad danie z włoską nutą.', 1, '/jpg/MAKARON_Z_KURCZAKIEM_I_PESTO_Z_RUKOLI.jpg'),
(3, 'TARTA Z BOCZKIEM, POREM I FASOLKĄ SZPARAGOWĄ', 'fasolka szparagowa – 200 g, wędzony boczek w plastrach (surowy) – 100 g, młody por – 1 szt., cebula dymka (ze szczypiorem) – 4 szt., czosnek – 1 ząbek, śmietanka 30% – 250 ml, żółtka – 3 szt., jajko – 1 szt., sól – 1 szczypta, pieprz biały – 3 szczypty, suszony tymianek – 2 szczypty, olej słonecznikowy – do smażenia', 'Szukasz oryginalnego pomysłu na obiad z fasolką szparagową? Wypróbuj przepis Karola na kruchą letnią tartę z sezonowymi warzywami i boczkiem!', 2, '/jpg/TARTA_Z_BOCZKIEM_POREM_I_FASOLKĄ_SZPARAGOWĄ.jpg'),
(4, 'TOSTY FRANCUSKIE Z KARMELIZOWANYMI OWOCAMI', 'słodka śmietanka 12% - 100 ml, jajka - 2 szt., cukier puder - ½ łyżeczki, cukier waniliowy lub ekstrakt waniliowy - 1 łyżeczka, cynamon - 2 szczypty, pełnoziarnisty chleb tostowy - 8 kromek, olej kokosowy do smażenia', 'Tosty na słodko? Deser idealny! Wypróbuj połączenia pełnoziarnistego pieczywa z czekoladą i karmelizowanymi owocami.', 2, '/jpg/TOSTY_FRANCUSKIE_Z_KARMELIZOWANYMI_OWOCAMI.jpg'),
(5, 'SAŁATKA Z KACZKĄ, GRUSZKĄ I BURACZKIEM', 'gruszka – 1 szt., orzechy nerkowca – 50 g, miks sałat z rukolą lub roszponką – 1 opakowanie, ugotowany burak – 1 szt., ser lazur – 100 g, miód – 1 łyżeczka', 'Oryginalna francuska sałatka z kaczką w towarzystwie orzeźwiającej gruszki i aromatycznego buraka.', 2, '/jpg/SAŁATKA_Z_KACZKĄ_GRUSZKĄ_I_BURACZKIEM.jpg'),
(6, 'WOLNO PIECZONA KARKÓWKA W PRZYPRAWACH KORZENNYCH', 'karkówka – 1 kg, miód – 2 łyżki, musztarda Dijon – 2 łyżeczki, czosnek – 1 ząbek, mielony kardamon – 2 łyżeczki, mielony cynamon – 1 łyżeczka, olej rzepakowy – 1 łyżka, skórka starta z 1 pomarańczy, sok wyciśnięty z 1 pomarańczy', 'Jej wyjątkowy, korzenny smak zawdzięczamy doskonałej marynacie i długiemu pieczeniu. Wykorzystaj świąteczny czas, by podać bliskim karkówkę według przepisu Karola Okrasy!', 3, '/jpg/WOLNO_PIECZONA_KARKÓWKA_W_PRZYPRAWACH_KORZENNYCH.jpg'),
(7, 'NAJLEPSZY ROSÓŁ', 'pietruszka – 3 szt., seler – ½ szt., marchewka – 2 szt., por – 1 szt., cebula – 1 szt., kacze uda – 2 szt., kurczak (cała tuszka) – 1 szt., olej roślinny – 1 łyżka, świeży lubczyk – 2 łyżki + kilka listków do dekoracji, zimna woda – 3 l, pieprz – 1 szczypta, ziele angielskie – 4 ziarenka, liście laurowe – 4 szt.', 'Szukasz przepisu na najlepszy rosół? Przygotuj go na bazie drobiowego mięsa i pieczonych warzyw, korzystając z receptury Karola Okrasy!', 3, '/jpg/NAJLEPSZY_ROSÓŁ.jpg');
